# This is a basic workflow to help you get started with Actions

name: Tokenise environment variables

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'workflows/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  TSServerToken : "xTSSERVERx"
  SQLInstanceToken : "xSQLINSTANCEx"
  SQLUserToken : "xSQLUSERx"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # De-reference any environment specific variables
  dereference:
    runs-on: ubuntu-latest
    environment: DEREFERENCE
    permissions:
      contents: write
    steps:
          
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: show env variable
        run: echo TSServer token, ${{env.TSServerToken}}
        
      - name: show DEREFERENCE TSSERVER
        run: echo TSServer value, ${{ vars.TSSERVER}}
        
      - name: Find and Replace TSSERVER in Rules
        uses: jacobtomlinson/gha-find-replace@3.0.5
        with:
          find: "${{vars.TSSERVER}}"
          replace: "${{env.TSServerToken}}"
          include: "Rules/**"
          regex: true    
          
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
  
  # This workflow contains a single job called "build"
  call-create-release-DEV:
    # Call the reusable workflow
    uses: AlexXeno/TestConfig/.github/workflows/CreateRelease.yml@main
    with:
      environment: DEV
      TSServerToken: ${env.TSServerToken}
      SQLInstanceToken: ${env.SQLInstanceToken{
      SQLUserToken: ${env.SQLUserToken}
        
  buildSIT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: SIT

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, ${{ vars.TSSERVER}} world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
