# This is a basic workflow to help you get started with Actions

name: Create Config Releases

# Controls when the workflow will run
on:
  # Triggers the workflow on release
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Create the various releases
  call-create-release-DEV:
    # Call the reusable workflow
    uses: AlexXeno/TestConfig/.github/workflows/CreateRelease.yml@main
    with:
      environment: DEV
      # apparently there is a bug in re-usable workflows that stop variables from working
      TSServerToken: "xTSSERVERx"
      SQLInstanceToken: "xSQLINSTANCEx"
      SQLUserToken: "xSQLUSERx"
  call-create-release-SIT:
    needs: [call-create-release-DEV]
    # Call the reusable workflow
    uses: AlexXeno/TestConfig/.github/workflows/CreateRelease.yml@main
    with:
      environment: SIT
      # apparently there is a bug in re-usable workflows that stop variables from working
      TSServerToken: "xTSSERVERx"
      SQLInstanceToken: "xSQLINSTANCEx"
      SQLUserToken: "xSQLUSERx"
