name: Test Release action

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Runs on Published
      run: echo ${{github.event}}
    - name: Runs on Published 2
      if: 'github.event.published'
      run: echo "This is a Publish"
    - name: Runs on Pre-Release
      if: 'github.event.prerelease'
      run: echo "This is a Pre-Release"
    - name: Runs on Release
      if: '!github.event.prerelease'
      run: echo "This is a Release"
